server:
  port: 8085

spring:
  webflux:
    base-path: webflux-mongodb
  application:
    name: webflux-mongodb-service

  data:
    mongodb:
      database: myMongoDb
      port: 27017    
    
eureka:
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

app:
  eureka-username: u
  eureka-password: p 

auth:
  svcKey: webflux-mongodb-1234-5678  
  
environment: prod 

springdoc:
  open-api:
    name: webflux-ui
    email: s@a.com
    version: '@springdoc.version@'
    license.name: license-name
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    use-root-path: true  

   
