server:
  port: 8084
  servlet:
   context-path: /dept

spring:
  cloud:
    config:
      enabled: false
  application:
    name: department-service
    
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: c##ding
    password: peardoor807x
    
    hikari:
      connection-timeout: 250000
      idle-timeout: 300000
      max-lifetime: 1000000
      maximum-pool-size: 24    

jpa:
  hibernate:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    ddl-auto: none
    
eureka:
  client:
    enabled: false
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}         
          
logging:
  pattern: 
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{15}) - %msg %n"

springdoc:
  api-docs:
   path: /v3/api-docs
  swagger-ui:
   path: /v3/swagger-ui.html  
  open-api:
    name: openApi Test
    email: roy@example.com
    license.name: my license 3.0
    
   
auth:
  svcKey: dep-1234-5678  
  
environment: local 

schedule:
  cron:
    expression: 0 10 19 2 2 ?
  fixedRate:
    in:
      milliseconds: 1000
  fixedDelay:
    in:
      milliseconds: 1000 

app:
  jwt-secret: my-secret

app-jwt-expiration-milliseconds: 711100000
  
   