server:
  port: 8083
  servlet:
   context-path: /emp
    
eureka:
  client:
    enabled: false
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}         

spring:
  cloud:
    config:
      enabled: false
  application:
    name: employee-service
    
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: c##ding
    password: peardoor807x

  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.Oracle12cDialect
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    
logging:
  pattern: 
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{15}) - %msg %n"

springdoc:
  api-docs:
   path: /v3/api-docs
  swagger-ui:
   path: /v3/swagger-ui.html  
   
auth:
  svcKey: emp-1234-5678   

app:
  jwt-secret: my-secret

app-jwt-expiration-milliseconds: 711100000

feign:
  client:
    config:
      department-service:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        defaultRequestHeaders:
          X-SVC-KEY: dep-1234-5678
  
environment: local  
   