server:
  port: 8087
  servlet:
    context-path: /batch

spring:
  application:
    name: batch-service
  main:
    allow-circular-references: true
    
  batch:
    job:
      enabled: false
      initialize-schema: always
    
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: c##ding
    password: peardoor807x

jpa:
  hibernate:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    ddl-auto: none
    
eureka:
  client:
    enabled: false
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
          
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  api-docs:
   path: /v3/api-docs
  swagger-ui:
   path: /v3/swagger-ui.html  
   
file:
 input:  coffee-list.csv
 
schedule:
 cron:
  expression: 0 15 10 15 * ?
 fixedRate:
  in:
   milliseconds: 1000
 fixedDelay:
  in:
   milliseconds: 1000 
   
auth:
  svcKey: batch-1234-5678   
  
app:
  jwt-secret: my-secret

app-jwt-expiration-milliseconds: 711100000

environment: local     