server:
  port: 8083

spring:
  cloud:
    config:
      enabled: true
  application:
    name: employee-service
    
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: c##ding
    password: peardoor807x

jpa:
  hibernate:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    ddl-auto: none
    
eureka:
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}
          
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  api-docs:
   path: /v3/api-docs
  swagger-ui:
   path: /v3/swagger-ui.html  
   
auth:
  svcKey: emp-1234-5678   
  
feign:
  client:
    config:
      DEPARTMENT-SERVICE:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        defaultRequestHeaders:
          X-SVC-KEY: dep-1234-5678

environment: prod  

app:
  eureka-username: u
  eureka-password: p
  jwt-secret: my-secret

app-jwt-expiration-milliseconds: 711100000
  
  