server:
  port: 8086
  servlet:
    context-path: /mvc-mongodb

spring:
  application:
    name: mvc-mongodb-service

  data:
    mongodb:
      database: myMongoDb
      port: 27017    
    
eureka:
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
          
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  api-docs:
   path: /v3/api-docs
  swagger-ui:
   path: /v3/swagger-ui.html  
  open-api:
    name: openApi Test
    email: roy@example.com
    license.name: my license 3.0
    
   
auth:
  svcKey: mvc-mongodb-1234-5678  
  
environment: prod

inter-microservice:
  webflux-mongodb-service: http://webfluxmongodb-service/student/
  employee-service: http://employee-service/employee/
   