server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/royzding/config-files
          search-paths:
          - config-three
          username: royzding@gmail.com
          password: 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
          ignore-local-ssh-settings: true
     
