server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/royzding/spring-three-projects
          search-paths:
          - config-service/src/main/resources/config
          username: royzding@gmail.com
          password: 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
          ignore-local-ssh-settings: true
     
