server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        bootstrap: true
        native:
          search-locations: file:///C:/workspace-4.19.0/spring-three-projects/config-files
     
