server:
  port: 8085

eureka:
 client:
  enabled: false
  registerWithEureka: false
  fetchRegistry: false
  serviceUrl:
    defaultZone: http://localhost:8761/eureka
 instance:
  hostname: localhost
  instance-id: ${spring.application.name}:${server.port}
  
spring:
  webflux:
    base-path: webflux-mongodb
  application:
    name: webflux-mongodb-service
  cloud:
    config:
      enabled: false
  main:
    web-application-type: reactive
      
  data:
    mongodb:
      database: myMongoDb
      port: 27017    
    
logging:
 pattern: 
  console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{15}) - %msg %n"

springdoc:
  api-docs:
   path: /v3/api-docs
  swagger-ui:
   path: /v3/swagger-ui.html  
  open-api:
    name: openApi Test
    email: roy@example.com
    license.name: my license 3.0

auth:
  svcKey: webflux-mongodb-1234-5678  
  
app:
  jwt-secret: my-secret

app-jwt-expiration-milliseconds: 711100000

environment: local  

   